(
    RESTART,
    SHOW_MENU_BUTTONS,
    GET_TOKEN_ARGS,
    DEPLOY_TOKEN1,
    START_DEPLOYMENT,
    LOW_GAS_FEE,
    ADD_LIQ,
    LOCK_LIQ,
    DEL_WALLET,
    GENERATE_NEW_WALLET,
    GET_TOKEN_TAX_INFO,
    GET_TOKEN_INFO,
    GET_LIQ_INFO,
    TRANSFER_FUNDS
) = range(14)
